### ISSUE TITLE
ParseAndAnalyze() doesn't catch schema mismatch of tabular params used by invoke command

### ISSUE THREAD

**Issue by motoko89** [mattwar/Kusto.Toolkit#28]
The following commands doesn't return error but it should:
``````
.create-or-alter function MyTestA(T:(commandId: long,ring:long))
{
    T
    | where ring == 1
}
``````
``````
.create-or-alter function MyTest(T:(actorId:long))
{
    T
    | invoke MyTestA()
}
``````

The code I use:
``````
foreach (string command in commands)
{
    var globals = await defaultSymbolLoader.AddOrUpdateDefaultDatabaseAsync(GlobalState.Default, databaseNameString);
    var code = KustoCode.ParseAndAnalyze(command, globals);
    // load databases referenced by query that are not already included in globals
    var resolver = new SymbolResolver(defaultSymbolLoader);
    var updatedCode = await resolver.AddReferencedDatabasesAsync(code);
    
    var diagnostics = updatedCode.GetDiagnostics();
    if (diagnostics.Count > 0)
    {
        Console.WriteLine("Error");
    }
}
``````

Could you please help? Thanks in advance

**Comment by mattwar** [comment]
Do you have function MyTestA() already defined in the database as MyTestA(T: (actorId: long))?

Did you expect that after analyzing the first create-or-alter command, that that the representation of MyTestA would have been updated?

This does not happen because the parser is not running the query, only analyzing it.  There is no correspondence between the two commands being analyzed, even when you analyze them in order.

There is, however, afeature in Kusto.Toolkit, the ApplyCommand extension method, that will identify the changes in schema that the command represents and apply that change to the global state as if the command had been executed.  

After you analyze the first command you can apply it to the globals to change the definition of the function for when you analyze the second command. 

```
foreach (var command in commands)
{
     // analyze command, etc.

    globals = globals.ApplyCommand(command);
}
```

**Comment by motoko89** [comment]
No, the function `MyTestA()` hasn't been created in the database. So based on your suggestion, I should move `globals` out of the `foreach` loop and and update it through `ApplyCommand` at the end of the loop?
``````
var globals = await defaultSymbolLoader.AddOrUpdateDefaultDatabaseAsync(GlobalState.Default, databaseNameString);
foreach (string command in commands)
{
    var code = KustoCode.ParseAndAnalyze(command, globals);
    // load databases referenced by query that are not already included in globals
    var resolver = new SymbolResolver(defaultSymbolLoader);
    var updatedCode = await resolver.AddReferencedDatabasesAsync(code);
    
    var diagnostics = updatedCode.GetDiagnostics();
    if (diagnostics.Count > 0)
    {
        Console.WriteLine("Error");
    }
   else
   {
      globals = globals.ApplyCommand(command);
   }
}
``````

**Comment by mattwar** [comment]
Yes.  Also, don't make a new Resolver inside the loop.
